// EmerBeats catalog — generated by the admin panel. Keep this file next to emerbeats.html.
window.STORE_DATA = {
  "tgLink": "https://t.me/EmerBeatsBot",
  "adminPin": "1234",
  "albums": [],
  "kits": [],
  "licenses": [
    {
      "id": "mp3",
      "name": "MP3 LEASE",
      "mult": 1,
      "tagline": "Tagless MP3",
      "terms": [
        "Untagged MP3 file",
        "Up to 50,000 streams",
        "1 music video",
        "2 radio stations"
      ]
    },
    {
      "id": "wav",
      "name": "WAV LEASE",
      "add": 15,
      "tagline": "WAV + MP3",
      "terms": [
        "WAV + MP3 files",
        "Up to 150,000 streams",
        "1 music video",
        "Distribute 5,000 copies"
      ]
    },
    {
      "id": "stems",
      "name": "TRACKOUT",
      "add": 45,
      "tagline": "Full Stems",
      "terms": [
        "Track stems + WAV + MP3",
        "Up to 500,000 streams",
        "Unlimited radio",
        "For mix engineers"
      ]
    },
    {
      "id": "unlimited",
      "name": "UNLIMITED",
      "add": 90,
      "tagline": "Unlimited use",
      "terms": [
        "Stems + WAV + MP3",
        "Unlimited streams & sales",
        "Unlimited radio",
        "Non-exclusive"
      ]
    },
    {
      "id": "exclusive",
      "name": "EXCLUSIVE",
      "mult": 10,
      "tagline": "Own it fully",
      "terms": [
        "Full ownership transfer",
        "Beat pulled from store",
        "Every file delivered",
        "Unlimited everything"
      ]
    }
  ]
};
